language: node_js

node_js:
  - 6
  - 7
  - 8

notifications:
  email: false
  slack:
    secure: svP3C2MV/WNQMJGVQ9pisGbwWTfVaMp2AApfx4JSTTcDFNXrerdwTSgp1kkOsHsf2SB+qMMNRjuNodGtsnbsJ/JwEIRQtN1zOvk5+iS3mE9THeh7KOCaGnGQifjOobH7KPCXlQomktGrQY0jCKbRZLATYFYrh2g3BvhuFtkBNg7V9XHD9468mHg2buaimt8DAc29iA/iFz1Ay6xfUvbx0wDQAMK6ixBIM0/7hkar/MxOs7NkeQpWogqEncs3YjzG740Tx5oRly6KlPysbqUBu2Mid6wH2oM0NusveZ5dzxdK5AzmayNQq1aow3lAx4yDFa2gjMtn950fG5MJHBEiDiC5TJZj0ildQaql+UVTIutGQRQAx5vM0PzWCknUc2XxPG1Nb9w7XasJZQJgfuI8YxwWLrx1UyFyFUu+5fcPNrrESJK61BhOJHcMP0g4wpiqxhYBJjVIWRTHOuE9yTRQLybp205xnPkXHrB2E8XnDMM1llSAeK2pSYY+DjXx/i4z/zj2WdrCqrKpL5m2x2/kY6eL7lCq7767qJsQ1f5USxz1nLuakxA/i6IsQ0thXLSR0GjGLfmmSLyfvKP11/xdEIj3LN2G5U/ulQtkECE1rCGdKXuBgsNKNQ7Jgl26x7dKuC8TbC+mpAT1uctr3iEhNcIF0WsT7bb7BN6+0VDCo88=
